FROM python:3.12-slim

WORKDIR /app-tests

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir app
COPY app/app.py app/
COPY app/database_manager.py app/
COPY app/user_interface.py app/
COPY app/__init__.py app/

RUN mkdir tests

COPY tests/test_database_manager.py tests/
COPY tests/__init__.py tests/

CMD ["python", "-m", "unittest", "discover", "tests"]